"""empty message

Revision ID: d6abea920ab5
Revises: 
Create Date: 2023-07-09 21:57:00.926008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd6abea920ab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'city',
        sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feature',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'store',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('city_id', sa.Uuid(as_uuid=False), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('start_time_local', sa.Time(), nullable=False),
        sa.Column('end_time_local', sa.Time(), nullable=False),
        sa.Column(
            'time_zone',
            sa.Enum(
                'KALININGRAD',
                'MOSCOW',
                'KIROV',
                'SAMARA',
                'ULYANOVSK',
                'SARATOV',
                'ASTRAKHAN',
                'YEKATERINBURG',
                'OMSK',
                'KRASNOYARSK',
                'NOVOSIBIRSK',
                'TOMSK',
                'NOVOKUZNETSK',
                'BARNAUL',
                'IRKUTSK',
                'YAKUTSK',
                'CHITA',
                'VLADIVOSTOK',
                name='timezone',
            ),
            nullable=False,
        ),
        sa.Column(
            'status', sa.Enum('OPEN', 'CLOSED', name='openstatus'), nullable=False
        ),
        sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='fk_store_city'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'storefeature',
        sa.Column('store_id', sa.Integer(), nullable=False),
        sa.Column('feature_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['feature_id'],
            ['feature.id'],
        ),
        sa.ForeignKeyConstraint(
            ['store_id'],
            ['store.id'],
        ),
        sa.PrimaryKeyConstraint('store_id', 'feature_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storefeature')
    op.drop_table('store')
    op.drop_table('feature')
    op.drop_table('city')
    # ### end Alembic commands ###
